name: Gitlab Runner Service
#on: [repository_dispatch,push]

on: [repository_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize Build Space
        uses: edersonbrilhante/gitlab-runner-action@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'

      - name: Gitlab Runner
        uses: TheFoundation/gitlab-runner-action@main
        with:
          registration-token: "${{ secrets.TOKEN }}"
          docker-image: "docker:19.03.12"
          name: ${{ github.run_id }}
          tag-list: "${{ github.event.client_payload.job_id }}"
